apiVersion: v1
kind: ServiceAccount
metadata:
  name: ogrenci-sistemi
  namespace: ogrenci-sistemi
  labels:
    app: ogrenci-sistemi

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ogrenci-sistemi-role
  namespace: ogrenci-sistemi
  labels:
    app: ogrenci-sistemi
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ogrenci-sistemi-rolebinding
  namespace: ogrenci-sistemi
  labels:
    app: ogrenci-sistemi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ogrenci-sistemi-role
subjects:
  - kind: ServiceAccount
    name: ogrenci-sistemi
    namespace: ogrenci-sistemi
